---
- name: Zabbix test rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Run playbook to turn on httpd
      # A noter que les tags avec des "-" ne sont pas accceptés
      condition: >-
        event.payload.host_groups contains("Virtual machines") and 
        event.payload.host_host is select("==","nboweb") and
        event.payload.event_tags.remediation is defined
      action:
        run_job_template:
          name: apache-remediate
          organization: Default
          job_args:
            limit: "{{ event.payload.host_host }}"

    - name: Debug
      condition: event.payload is defined
      action:
        debug:
          msg:
