---
- name: Zabbix test rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Run playbook to turn on httpd
      condition: event.payload is defined
      action:
        debug:
