---
- name: Listen for events on a webhook
  hosts: localhost

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: Send message to docker logs
      condition: event.payload.message == "hello"
      action:
        run_playbook:
          name: hello-world-playbook.yml
          extra_vars:
            user: "{{event.payload.user}}"
